### ISSUE TITLE
Forgery + FactoryGirl Definition Proxy => undefined method `user_name' for #<FactoryGirl::Declaration::Static:...>

### ISSUE THREAD

**Issue by s1kx** [thoughtbot/factory_bot#399]
I am using forgery 0.5.0 with factory_girl_rails 3.5.0 in my project. This usually always worked too, but now that I am trying this in another project, with the following factory:

``` ruby
# spec/factories/users.rb

FactoryGirl.define do
  factory :user do
    email { "#{username}@#{Forgery(:internet).domain_name}" }
    sequence(:username) { |n| "#{Forgery(:internet).user_name}_#{n}" }
    password { Forgery(:basic).password(at_least: 6, at_most: 30, allow_special: true) }

    first_name { Forgery(:name).send("#{gender}_first_name") }
    last_name { Forgery(:name).last_name }

    gender { %w( male female ).sample }

    biography { Forgery(:lorem_ipsum).sentence }

    location_places_reference { SecureRandom.urlsafe_base64 }
    location_latitude { rand }
    location_longitude { rand }
    location_city { Forgery(:address).city }
    location_region { Forgery(:address).state_abbrev }
    location_country { Forgery(:address).country }

    phone_country_code { 1 + rand(900) }
    phone_number { Forgery(:address).phone }
  end
end
```

... and the following model specs ...

``` ruby
require 'spec_helper'

describe User do

  subject { build(:user) }

  it { should be_valid }

  describe "validations" do
    it { should validate_presence_of(:email) }
    it "ensures emails are unique" do
      create(:user) # create a user to test against
      should validate_uniqueness_of(:email)
    end
    it { should validate_format_of(:email).with("test@example.com") }
    it { should validate_format_of(:email).not_with("invalidemail") }

    it { should validate_presence_of(:password) }
    it { should ensure_length_of(:password).is_at_least(4).is_at_most(40) }

    it { should validate_presence_of(:first_name) }
    it { should ensure_length_of(:first_name).is_at_least(2) }
    it { should validate_presence_of(:last_name) }
    it { should ensure_length_of(:last_name).is_at_least(2) }

    it { should validate_presence_of(:gender) }
    it { should ensure_inclusion_of(:gender).in_array(%w(male female)) }

    it { should ensure_length_of(:biography).is_at_most(140) }

    it { should ensure_inclusion_of(:phone_country_code).in_range(1..1000).allow_blank }
    it { should validate_format_of(:phone_number).with("12345678") }
    it { should validate_format_of(:phone_number).with("A-12345678!") } # Validate that the accessor strips other chars

    it { should validate_presence_of(:location_latitude) }
    it { should validate_numericality_of(:location_latitude) }
    it { should validate_presence_of(:location_longitude) }
    it { should validate_numericality_of(:location_longitude) }
    it { should validate_presence_of(:location_city) }
    it { should validate_presence_of(:location_country) }
    it { should validate_presence_of(:location_places_reference) }
  end

  # rest omitted...
end
```

... I am getting this error for all related specs (same for other factories that use Factory(:internet).user_name):

```
patrick@dev ~/... $ b rspec spec/models/user_spec.rb -b
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

Failures:

  1) User 
     Failure/Error: subject { build(:user) }
     NoMethodError:
       undefined method `user_name' for #<FactoryGirl::Declaration::Static:0x000000044dfc20>
     # ./spec/factories/users.rb:6:in `block (3 levels) in <top (required)>'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/sequence.rb:23:in `call'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/sequence.rb:23:in `next'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/definition_proxy.rb:115:in `block in sequence'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute/dynamic.rb:14:in `instance_exec'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute/dynamic.rb:14:in `block in to_proc'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/evaluator.rb:62:in `instance_exec'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/evaluator.rb:62:in `block in define_attribute'
     # ./spec/factories/users.rb:5:in `block (3 levels) in <top (required)>'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute/dynamic.rb:14:in `instance_exec'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute/dynamic.rb:14:in `block in to_proc'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/evaluator.rb:62:in `instance_exec'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/evaluator.rb:62:in `block in define_attribute'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:62:in `get'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/strategy/build.rb:9:in `result'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/factory.rb:42:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/active_support/notifications.rb:125:in `instrument'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:19:in `block in define_singular_strategy_method'
     # ./spec/models/user_spec.rb:5:in `block (2 levels) in <top (required)>'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/subject.rb:51:in `instance_eval'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/subject.rb:51:in `subject'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/subject.rb:69:in `should'
     # ./spec/models/user_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example.rb:87:in `instance_eval'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example.rb:87:in `block in run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example.rb:195:in `with_around_each_hooks'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example.rb:84:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example_group.rb:353:in `block in run_examples'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example_group.rb:349:in `map'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example_group.rb:349:in `run_examples'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/example_group.rb:335:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/command_line.rb:28:in `map'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/command_line.rb:28:in `block in run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/reporter.rb:34:in `report'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/command_line.rb:25:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/runner.rb:69:in `run'
     # /home/patrick/.rbenv/versions/1.9.3-rc1/lib/ruby/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/runner.rb:10:in `block in autorun'
```

I have read in another similar ticket (229) that e.g. `rand` is only usable as `Random.rand` because the DefinitionProxy undefines all methods on Kernel. I don't understand how that would apply here though as I am explicitely calling it on the Forgery module (and I have tried it with Forgery::Internet in place of Forgery(:internet) too).
